name: HB
description: stuff

port:        4000
baseurl:     /
url:         http://bruant.info

articles:      ./_articles
articles_dest: ./articles

exclude:     [README.md, bsd.txt, cc-by-sa-3.0.txt]

future:      true
pygments:    true
markdown:    maruku
permalink:   date

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


